name: javabrake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11, 13, 14, 15, 17]

    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: Test
        run: ./gradlew build
